import { Product } from "../models/cargo.type";

export const PRODUCTS_DADA: Product[] = [
  {
    ProdId: "1",
    ProdName: "Brown Brim",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1477064996809-dae46985eee7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    ProdPrice: 25,
    ProdDescription:
      "rebvevj4e5emreuiwvnerulbnebthietnwovrlabuariyewlgvwavnwailrvbyrwabvnvielwbvywragutvrwbtenbilncewgvbwyraenvwuth cwgytgnv3cyigftycyinert",
    ProdBelongsTo: "hat",
  },
  {
    ProdId: "2",
    ProdName: "Blue Beanie",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1578019857395-bcfccf0ffb30?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    ProdPrice: 18,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "hat",
  },
  {
    ProdId: "3",
    ProdName: "Brown Cowboy",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1579847036628-16ad08c77783?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    ProdPrice: 35,
    ProdDescription: "rebveberbrbtrjr5em",
    ProdBelongsTo: "hat",
  },
  {
    ProdId: "4",
    ProdName: "Grey Brim",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1470320137052-e6968bda0539?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1932&q=80",
    ProdPrice: 25,
    ProdDescription: "rebverehrebtrjr5em",
    ProdBelongsTo: "hat",
  },
  {
    ProdId: "5",
    ProdName: "Green Beanie",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1576684309962-b57327502311?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    ProdPrice: 18,
    ProdDescription: "rebvevbetj4ebrebtrjr5em",
    ProdBelongsTo: "hat",
  },
  {
    ProdId: "6",
    ProdName: "Palm Tree Cap",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1534215754734-18e55d13e346?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=704&q=80",
    ProdPrice: 14,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "hat",
  },
  {
    ProdId: "7",
    ProdName: "Red Beanie",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1614544206786-2e38c851ed4c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    ProdPrice: 18,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "hat",
  },
  {
    ProdId: "8",
    ProdName: "maga Cap",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1622927569053-d7896a1e9c80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
    ProdPrice: 14,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "hat",
  },
  {
    ProdId: "9",
    ProdName: "Blue Snapback",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1598539962077-e4185f37104f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80",
    ProdPrice: 16,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "hat",
  },

  {
    ProdId: "10",
    ProdName: "Pink robe",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1591900947067-851789555ef3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    ProdPrice: 220,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "coat",
  },
  {
    ProdId: "11",
    ProdName: "black long sleeve coat",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1558718932-c6dfc209f6fb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
    ProdPrice: 280,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "coat",
  },
  {
    ProdId: "12",
    ProdName: "fur coat",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1545912193-41b5212f30ee?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    ProdPrice: 110,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "coat",
  },
  {
    ProdId: "13",
    ProdName: "knitted coat",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1610871307513-c94254a035b6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80",
    ProdPrice: 160,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "coat",
  },
  {
    ProdId: "14",
    ProdName: "pilot jacket",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1583854608682-94147497bd27?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    ProdPrice: 160,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "coat",
  },
  {
    ProdId: "15",
    ProdName: "yellow jacket",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1599407950360-8b8642d423dc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Njl8fGNvYXR8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    ProdPrice: 160,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "coat",
  },
  {
    ProdId: "16",
    ProdName: "leather jacket",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1552699344-8718b46cb5ed?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTI0fHxjb2F0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProdPrice: 190,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "coat",
  },
  {
    ProdId: "17",
    ProdName: "waterproof jacket",
    ProdImageUrl:
      "https://images.unsplash.com/photo-1512755051947-dea0029e93ad?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    ProdPrice: 200,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "coat",
  },
  {
    ProdId: "18",
    ProdName: "LINEN BLEND EASY TROUSERS",
    ProdImageUrl:
      "https://image.uniqlo.com/UQ/ST3/eu/imagesgoods/454542/item/eugoods_30_454542.jpg?width=330&impolicy=quality_70&imformat=chrome",
    ProdPrice: 125,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "19",
    ProdName: "Blue Jean Jacket",
    ProdImageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
    ProdPrice: 90,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "20",
    ProdName: "Grey Jean Jacket",
    ProdImageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    ProdPrice: 90,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "21",
    ProdName: "Brown Shearling",
    ProdImageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
    ProdPrice: 165,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "22",
    ProdName: "Tan Trench",
    ProdImageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    ProdPrice: 185,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "23",
    ProdName: "Blue Tanktop",
    ProdImageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
    ProdPrice: 25,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "24",
    ProdName: "Floral Blouse",
    ProdImageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
    ProdPrice: 20,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "25",
    ProdName: "Floral Dress",
    ProdImageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
    ProdPrice: 80,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "26",
    ProdName: "Red Dots Dress",
    ProdImageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
    ProdPrice: 80,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "27",
    ProdName: "Striped Sweater",
    ProdImageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    ProdPrice: 45,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "women",
  },
  {
    ProdId: "28",
    ProdName: "Yellow Track Suit",
    ProdImageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
    ProdPrice: 135,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "men",
  },
  {
    ProdId: "29",
    ProdName: "White Blouse",
    ProdImageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
    ProdPrice: 20,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "men",
  },
  {
    ProdId: "30",
    ProdName: "Camo Down Vest",
    ProdImageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
    ProdPrice: 325,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "men",
  },
  {
    ProdId: "31",
    ProdName: "Floral T-shirt",
    ProdImageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
    ProdPrice: 20,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "men",
  },
  {
    ProdId: "32",
    ProdName: "Black & White Longsleeve",
    ProdImageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
    ProdPrice: 25,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "men",
  },
  {
    ProdId: "33",
    ProdName: "Pink T-shirt",
    ProdImageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
    ProdPrice: 25,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "men",
  },
  {
    ProdId: "34",
    ProdName: "Jean Long Sleeve",
    ProdImageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
    ProdPrice: 40,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "men",
  },
  {
    ProdId: "35",
    ProdName: "Burgundy T-shirt",
    ProdImageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
    ProdPrice: 25,
    ProdDescription: "rebvevj4ebrebtrjr5em",
    ProdBelongsTo: "men",
  },
];
